{
  "ESPETINHO DE CARNE": "UN",
  "ESPETINHO DE FRANGO": "UN",
  "ESPETINHO MISTO": "UN",
  "ESPETINHO BOVINO": "UN",
  "ESPETINHO DE PICANHA": "UN",
  "ESPETINHO DE CORAÇÃO": "UN",
  "ESPETINHO DE TULIPA": "UN",
  "ESPETINHO DE MEDALHÃO DE FRANGO": "UN",
  "ESPETINHO DE MEDALHÃO DE ALCATRA": "UN",
  "ESPETINHO DE FRANGO": "UN",
  "ESP MEDALHÃO DE QUEIJO COALHO": "UN",
   "ESPETINHO DE KAFTA": "UN",
    "ESPETINHO DE LOMBO": "UN",
     "ESPETINHO DE PANCETA": "UN",
      "ESPETINHO": "UN",
       "ESPETINHO DE LINGUIÇA": "UN",
        "ESPETINHO DE ALCATRA": "UN",
         "ESPETINHO BOVINO": "UN"

}